### PR TITLE
Add "why livecoms?" document/mini-paper

### PR DESCRIPTION
**Pull request by davidlmobley**
This adds an initial very preliminary draft of the "why livecoms?" document/mini-paper I put together that explains the philosophy. It still needs references and probably polishing, but hopefully it's to the point where it can benefit from edits.

@mrshirts , thoughts?

I'd love to get edits as a PR to my branch.

### CODE REVIEW

**Comment by mrshirts** [comment]
OK, added a PR with minor comments to your branch.

**Comment by davidlmobley** [comment]
@mrshirts - I think this is ready to merge. I've temporarily removed Dan Zuckerman until he has a chance to review and sign off as, since he hasn't even looked at this material at present, it is not fair to call him an author. I hope he'll like it, provide edits, and want to be on it, though.

**Comment by davidlmobley** [comment]
I also proposed minor edits to polish the website; I had meant to put this in a different PR, but, well, it's minor so it probably is fine here.

**Comment by davidlmobley** [comment]
OK, @mrshirts - I'll merge this one and you can pick up from here, though feel free to undo things if you think we screwed something up.

**Pull request merged**
