### PR TITLE
Add links to `about page`

### LINKED ISSUE #14: About the journal needs links
The "about the journal" page needs links to, er, expanded info about the journal -- probably the "Why LiveCoMS" document as well as the "paper-writing as code development" document, and a brief explanation of the fact that most of the info is at livecomsjournal.github.io.

### PR DESCRIPTION
**Pull request by davidlmobley**
This resolves #14 by adding additional links (and a bit more content) to the `about` page.

In the process I also found that we had editorial policy information here which has migrated to livecomsjournal.github.io, so I removed that information.

### CODE REVIEW

**Review by mrshirts — CHANGES_REQUESTED** [review]
LGTM except I don't think the "how paper writing is like code development" should be linked on the front page of the website; it's sort of tangential to the operation and purpose of the journal, unlike the vision document, which is more integral.  Linking it in the author instructions would be better.

**Comment by davidlmobley** [comment]
@mrshirts - this is not on the front page of the website, just the "about" page, which seemed to me the most suitable since this is an aspect of how the journal makes sense the way we've organized it (and is not part of our author instructions). But I can remove it.

**Comment by dmzuckerman** [comment]
I agree with @davidlmobley that linking to our editorial is appropriate for the About page.

**Comment by davidlmobley** [comment]
I have the editorial there. There is also a separate little blurb I wrote on how paper writing is like code development in some ways (e.g. how it can benefit from GitHub, etc.) -- see https://livecomsjournal.github.io/about/paper_code/ . The question was whether we should link to that one from About, too...

**Comment by dmzuckerman** [comment]
Sorry, brain failure!  (It's hard to be 50.)

I have a suggestion.  What if we just linked the phrase "regularly updated" to the code-development perpsective?  Or we could amend it slightly to, "regularly updated on github with community input" and link that.

**Comment by davidlmobley** [comment]
Good idea, @dmzuckerman ; doing a PR with this link.

**Pull request merged**
